version: "3"

services:
  db:
    image: postgres
    env_file:
      - ./university/.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: on-failure

  rabbit:
    image: rabbitmq:3-management-alpine
    env_file:
      - ./university/.env
    ports:
      - "5675:5672"
      - "15675:15672"
    restart: on-failure

  celery:
    build: .
    command: celery -A university worker -l info -B
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbit
      - db

  api:
    build: .
    command: >
      bash -c "python /usr/src/app/manage.py migrate &
      python /usr/src/app/manage.py generate_data &
      python /usr/src/app/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./university/.env
    depends_on:
      - db